package br.com.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class ErroController {
	@FXML
	private Label lblMsgErro;
	@FXML
	private Button btnErroFechar;

	// Event Listener on Button[#btnErroFechar].onAction
	@FXML
	public void erroFechar(ActionEvent event) {
		// TODO Autogenerated
	}
}
