package br.com.controller;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuItem;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TextField;

public class LayoutController implements Initializable{
	
	@FXML private TextField txtBuscaPedido;
	@FXML private Button btnBuscaPedido;
	@FXML private Button btnEditarPedido;
	@FXML private Button btnExcluirPedido;
	@FXML private TextField txtBuscaPedidoAcompa;
	@FXML private Button btnBuscaPedidoAcompa;
	@FXML private Button btnEditarPedidoAcomp;
	@FXML private Button btnExcluirPedidoAcomp;
	@FXML private DatePicker dpDataInicial;
	@FXML private DatePicker dpDataFinal;
	@FXML private Button btnFiltrar;
	@FXML private Label lblIni;
	@FXML private Label lblFim;
	
	@FXML private Menu mnVisualizar;
	@FXML private MenuItem miPedidoTel;
	@FXML private MenuItem miPedidos;
	@FXML private MenuItem miAcompa;
	@FXML private MenuItem miVendas;
	@FXML private MenuItem miFatura;
	@FXML private MenuItem miGrafiVendas;
	@FXML private MenuItem miTransp;
	@FXML private Tab tabTransp;
	@FXML private TabPane tpDesk;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		tpDesk.getSelectionModel().select(6);
		
		miPedidoTel.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(0);
			}
		});
		miPedidos.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(1);
			}
		});
		miAcompa.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(2);
			}
		});
		miVendas.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(3);
			}
		});
		miFatura.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(4);
			}
		});
		miGrafiVendas.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(5);
			}
		});
		miTransp.setOnAction(new javafx.event.EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
				tpDesk.getSelectionModel().select(6);
			}
		});
	}
	
	// Event Listener on Button[#btnBuscaPedido].onAction
	@FXML
	public void buscarPedido(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditarPedido].onAction
	@FXML
	public void editarPedido(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluirPedido].onAction
	@FXML
	public void excluirPedido(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBuscaPedidoAcompa].onAction
	@FXML
	public void buscarPedidoAcompa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditarPedidoAcomp].onAction
	@FXML
	public void editarPedidoAcomp(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnExcluirPedidoAcomp].onAction
	@FXML
	public void excluirPedidoAcomp(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFiltrar].onAction
	@FXML
	public void filtrarVendas(ActionEvent event) {
		System.out.println();
		System.out.println(dpDataInicial.getValue());
		System.out.println(dpDataFinal.getValue());
		
		lblIni.setText(dpDataInicial.getValue().toString());
		lblFim.setText(dpDataFinal.getValue().toString());
		
		dpDataInicial.setValue(null);
		dpDataFinal.setValue(null);
	}
	
}
